// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkyN6m8_q4Ej1vlFXskBy8ETKNKM-L3kE',
    appId: '1:384571088747:web:c3b098917ced300c9c762e',
    messagingSenderId: '384571088747',
    projectId: 'flutter-test-8f2dd',
    authDomain: 'flutter-test-8f2dd.firebaseapp.com',
    storageBucket: 'flutter-test-8f2dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQNed3YoUYihjwBpJrN-oR06CgI3AhH8E',
    appId: '1:384571088747:android:6615ad5df77e0bc09c762e',
    messagingSenderId: '384571088747',
    projectId: 'flutter-test-8f2dd',
    storageBucket: 'flutter-test-8f2dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6J3ohoJeOzLD1oE2UmzXpFfpQPEenMw',
    appId: '1:384571088747:ios:a1fcddf67f944e1d9c762e',
    messagingSenderId: '384571088747',
    projectId: 'flutter-test-8f2dd',
    storageBucket: 'flutter-test-8f2dd.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc6J3ohoJeOzLD1oE2UmzXpFfpQPEenMw',
    appId: '1:384571088747:ios:a1fcddf67f944e1d9c762e',
    messagingSenderId: '384571088747',
    projectId: 'flutter-test-8f2dd',
    storageBucket: 'flutter-test-8f2dd.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
